name: snapkit_image_url
description: Snapkit Image URL builder for Dart/Flutter
version: 1.0.0
homepage: https://github.com/snapkit-studio/snapkit-image-url-dart

environment:
  sdk: ^3.0.0

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
